//package Exam.src.ExceptionHandling0722;
//
//public class ExceptionTest3 {
//
//  //실행 순서는?
//  public static void main(String[] args) {
//
//    try {
//      System.out.println(1);
//      throw new MyException("내가 만든 예외");
//
//    } catch(MyException e){
//      System.out.println(e.getMessage());
//      e.printStackTrace();
//    }
//    System.out.println("종료");
//  }
//}
